name: .NET

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      configuration:
        description: "Build configuration"
        required: true
        default: "Release"
      branches:
        description: "Branches to build"
        required: true
        default: "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Branches: ${{ github.event.inputs.branches }}"
          echo "Configuration: ${{ github.event.inputs.configuration }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Event ref: ${{ github.event.ref }}"
          echo "Environment: ${{ github.event.environment }}"

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore